name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres-primary:
        image: timescale/timescaledb:2.17.2-pg18
        env:
          POSTGRES_DB: payflow
          POSTGRES_USER: dev
          POSTGRES_PASSWORD: dev
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U dev -d payflow"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      postgres-replica:
        image: timescale/timescaledb:2.17.2-pg18
        env:
          POSTGRES_DB: payflow
          POSTGRES_USER: dev
          POSTGRES_PASSWORD: dev
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
        ports:
          - 5433:5432
        options: >-
          --health-cmd "pg_isready -U dev -d payflow"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 25
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'temurin'
          cache: maven

      - name: Build and test
        run: mvn verify
        env:
          DB_WRITE_URL: jdbc:postgresql://localhost:5432/payflow
          DB_READ_URL: jdbc:postgresql://localhost:5433/payflow
          DB_USERNAME: dev
          DB_PASSWORD: dev
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          SPRING_KAFKA_BOOTSTRAP_SERVERS: localhost:9092